sonar.projectKey=aphichat1835-coder_neverdie-quest-helper
sonar.organization=aphichat1835-coder
sonar.projectName=NeverDie Quest Helper

sonar.sources=bot/src
sonar.tests=bot/test
sonar.test.inclusions=bot/test/**/*.js
sonar.javascript.lcov.reportPaths=bot/coverage/lcov.info
sonar.sourceEncoding=UTF-8
